<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Campaign\Module'                        => __DIR__ . '/Module.php',
    'Campaign\Controller\CampaignController' => __DIR__ . '/src/Campaign/Controller/CampaignController.php',
    'CampaignTest\Framework\TestCase'        => __DIR__ . '/tests/Campaign/Framework/TestCase.php',
    'CampaignTest\SampleTest'                => __DIR__ . '/tests/Campaign/SampleTest.php',
);
