<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<!-- Apple iOS and Android stuff (do not remove) -->
<meta name="apple-mobile-web-app-capable" content="no" />
<meta name="apple-mobile-web-app-status-bar-style" content="black">

<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- Required Stylesheets -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/reset.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/text.css" media="screen">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/fonts/ptsans/stylesheet.css" media="screen">

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/core/form.css" media="screen">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/core/login.css" media="screen">
<link rel="stylesheet" type="text/css" href="<? echo $this->basePath(); ?>/admin/css/core/button.css" media="screen">

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/mws.theme.css" media="screen">

<!-- JavaScript Plugins -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/jquery-1.7.1.min.js"></script>

<!-- jQuery-UI Dependent Scripts -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/jquery-ui-effecs.min.js"></script>

<!-- Plugin Scripts -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/placeholder/jquery.placeholder-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/validate/jquery.validate-min.js"></script>

<!-- Login Script -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/login.js"></script>

<?php echo $this->headTitle('Tee For All'); ?>

</head>

<body>
   <?php echo $this->content; ?> 
</body>
</html>