<div id="mws-navigation">
     <ul>
        <li>
           <a href="/admin/index" class="mws-i-24 i-list">Dashboard</a>
        </li>
                	
        <li>
           <a href="#" class="mws-i-24 i-list1">System</a>
           
           <ul class="closed" style="display: none;">
               <li class="active">
                   <a class="mws-i-24 i-cog" href="/admin/configuration">Configurations</a>
               </li>
               
               <li class="active">
               	   <a class="mws-i-24 i-email" href="/admin/email-templates">Email Templates</a>
               </li>
               
               <li class="active">
               	   <a class="mws-i-24 i-page" href="/admin/pages">Static Pages</a>
               </li>
           </ul>
        </li>
        
                    
        <li>
           <a href="#" class="mws-i-24 i-list2">Users</a>
                        
           <ul class="closed" style="display: none;">
              <li class="active">
                  <a class="mws-i-24 i-list2" href="/admin/users">Manage Users</a>
              </li>
				            
		      <li class="active">
		          <a class="mws-i-24 i-email" href="/admin/contact-user">Contact Sellers</a>
		      </li>
				            
			  <li class="active">
			  	  <a class="mws-i-24 i-email" href="/admin/contact-buyers">Contact Buyers</a>
			  </li>
           </ul>
        </li>
                    
               
        <li>
           <a href="#" class="mws-i-24 i-tspringcatg">T-Shirt</a>
              <ul class="closed" style="display: none;">
				  <li class="active">
				      <a class="mws-i-24 i-tspringcatg" href="/admin/discount">Manage Discount</a>
				  </li>
                        
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/icons">Manage Icons</a>
                  </li>
                              
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/products">Tshirt Products</a>
                  </li>
              </ul>
        </li>
                    
        <li>
           <a href="#" class="mws-i-24 i-tspringcatg">T-Shirt Size</a>
              <ul class="closed" style="display: none;">
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/tshirt-size">Manage Sizes</a>
                  </li>
              </ul>
        </li>
                                          
        <li>
           <a href="#" class="mws-i-24 i-tspringcatg">Campaigns</a>
              <ul class="closed" style="display: none;">
                  <li class="active">
                  	  <a class="mws-i-24 i-tspringcatg" href="/admin/campaign">Manage Campaigns</a>
                  </li>
               
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/campaign-live">Live Campaigns</a>
                  </li>
                  
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/campaign-success">Successful Campaigns</a>
                  </li>
                  
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/campaign-unsuccessful">Unsuccessful Campaigns</a>
                  </li>
                  
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/campaign-instructions">Instructions</a>
                  </li>
              </ul>
        </li>
                   
        <li>
           <a href="#" class="mws-i-24 i-tspringcatg">Payment Details</a>
              <ul class="closed" style="display: none;">
                  <li class="active">
                  	  <a class="mws-i-24 i-tspringcatg" href="/admin/payment">All Payment</a>
                  </li>
                  
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/expire">Expired Payment</a>
                  </li>
                  
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/active">Active Payment</a>
                  </li>
                  
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/charged">Charged Payment</a>
                  </li>
			  </ul>
        </li>
                   
        <li>
           <a href="#" class="mws-i-24 i-tspringcatg">Export Reports</a>
              <ul class="closed" style="display: none;">
                  <li class="active">
                      <a class="mws-i-24 i-tspringcatg" href="/admin/export">Shipping Report</a>
                  </li>
              </ul>
        </li> 
                  
              
    </ul>
</div>