<p>
 <div align="center" style="background-color:#CCC; width:600px; height:150px; border:#666 solid 1px; border-radius:5px; margin-bottom:70px;">
     <div align="left" style="margin-left:10px; padding-bottom:5px;">
    <?php if($this->status == '1') { ?>
    <label style="font-family:Corbel; font-size:18px; color:#030; ">
        Thank You!<br /><br />
        Your Account is activated successfully.
        To Access and Manage your account
        <a href="<?php $this->url('user', array('action' => 'login')); ?>" style="text-decoration:none; color:#333333;">
        Click Here</a> to Login.
         </label>
         <?php }
         if($this->status == '2') { ?>
    <label style="font-family:Corbel; font-size:18px; color:#030">
        <h3>Your Account already activated</h3>
        </label>
        <?php }
        if($this->status == '3') { ?>
    <label style="font-family:Corbel; font-size:18px; color:#030; ">
        <h3>The account activation link you are using is invalid or expired.</h3>
        <?php } ?>
    </div>
</div>
