<?php if ($this->testing == "") { ?>
<div id="loginas" class="work_section_two  mainprofile" style="display:block">
<?php } else {    ?>
<div id="loginas" class="work_section_two  mainprofile" style="display:none">
<?php } ?>
<form method="post" name="login" action="<?=$this->url('user', array('action'=>'login', 'l' => $this->l))?>">
    <div class="top10pxmargin " style="margin-top:0px;">
        <label class="myaccsubtitles">Email Address</label>
    </div>

    <div class="top5pxmargin ">
        <?php echo $this->form->email; ?>
    </div>

    <div class="top10pxmargin " >
        <label class="myaccsubtitles">Password</label>
    </div>

    <div class="top5pxmargin ">
        <?php echo $this->myform->password; ?>
    </div>

    <div class="top10pxmargin " >
        <a href="<?php echo $this->url('user', array('action' => 'forgotpassword')); ?>" style="text-decoration:none;">
            <label style="cursor:pointer;" >Forgot Your Password ?</label>
        </a>
    </div>
    <div class="top10pxmargin ">
        <input type="submit" name="loginbtn" id="loginbtn" value="Sign In Now" class="accbutton">
        <label style="color:#006853; font-size:16px; cursor:pointer;vertical-align:middle;" onclick="opennewdiv();">or Create New Account</label>
    </div>
</form>
</div>
<?php if ($this->testing != "") { ?>
<div id="signupas" class="work_section_two  mainprofile" style="display:block">
<?php } else { ?>
<div id="signupas" style="display:none" class="work_section_two  mainprofile">
<?php } ?>
<form method="post" name="signup" action="<?php echo $this->url('user', array('action'=>'signuped','l' => $this->l))?>">
    <div class="top10pxmargin " style="margin-top:0px;">
        <label class="myaccsubtitles">Public Name</label>
    </div>
    <div class="top5pxmargin ">
        <?=$this->myformsignup->publicname?>
    </div>

    <div class="top10pxmargin ">
        <label class="myaccsubtitles">Email Address</label>
    </div>
    <div class="top5pxmargin ">
        <?=$this->myformsignup->signupemailid?>
    </div>

    <div class="top10pxmargin ">
        <label class="myaccsubtitles">Password</label>
    </div>
    <div class="top5pxmargin ">
        <?=$this->myformsignup->signuppass?>
    </div>

    <div class="top10pxmargin ">
        <label class="myaccsubtitles">Confirm Password</label>
    </div>
    <div class="top5pxmargin ">
        <?=$this->myformsignup->signupcnfrmpass?>
    </div>

    <div class="top10pxmargin ">
        <input type="submit" name="loginbtn" style="width:240px" id="loginbtn" value="Create Your Account" class="accbutton">
        <label style="color:#006853; font-size:16px; cursor:pointer;vertical-align:middle;" onclick="opennewdiv();">or Already Have an Account</label>
    </div>

</form>
</div>

<script type="text/javascript">
function opennewdiv()
{
    if (document.getElementById('loginas').style.display=="block") {
        document.getElementById('signupas').style.display="block";
        document.getElementById('how_in_right').innerHTML='Create New Account';
        document.getElementById('loginas').style.display="none";
    } else {
        document.getElementById('signupas').style.display="none";
        document.getElementById('loginas').style.display="block";
        document.getElementById('how_in_right').innerHTML='Login';
    }
}
</script>