<?php if($this->form): ?>
<?php
    $form = $this->form;
    $form->prepare(); ?>
<div class="work_section_two  mainprofile" id="forgotpass">
    <form name="myform" id="myform" method="post" action="<?php echo $this->url('user', array('action' => 'resetpassword','data' => $this->hash))?>">
    <div class="top10pxmargin " style="margin-top:0px;">
        <label class="myaccsubtitles">Password</label>
    </div>
    <div class="top5pxmargin ">
        <?php echo $this->formElement($form->get('password')); ?>
        <div class="errmsg">
            <?php echo $this->formElementErrors($form->get('password')) ?>
        </div>
    </div>
    <div class="top10pxmargin ">
        <label class="myaccsubtitles">Confirm Password</label>
    </div>
    <div class="top5pxmargin ">
        <?php echo $this->formElement($form->get('configmpassword')); ?>
        <div class="errmsg">
            <?php echo $this->formElementErrors($form->get('configmpassword')) ?>
        </div>
    </div>
    <div class="top10pxmargin ">
        <input type="submit" name="loginbtn" id="loginbtn" style="width:260px" value="Reset Your Password" class="accbutton">
    </div>
    </form>
</div>
<?php endif; ?>
