<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>

<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Add New Pages</span>
    </div>
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" 
        action="<?php echo $this->url('admin', array('action' => 'save-page'))?>"
         method="post" novalidate="novalidate" class="mws-form">
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
            
            <div class="mws-form-inline">
                <div class="mws-form-row">
                    <label>Title :</label>
                    <div class="mws-form-item large">
                        <?php echo $this->formRow($this->form->get('page_title')); ?>
                    </div>
                </div>
                
                <div class="mws-form-row">
                	<label>Content</label>
                		<div class="mws-form-item">
                    	<?php echo $this->formTextarea($this->form->get('page_content')); ?>
                		</div>
            	</div>
            	
            	<div class="mws-button-row">
                	<?php echo $this->formSubmit($this->form->get('add_pages_submit')); ?>
            	</div>
            </div>
        </form>
    </div>    	
</div> 