<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Add T-Shirt Size</span>
    </div>
    
    <div class="mws-panel-body">
    <?php 
        $this->form->setAttribute('action', $this->url('admin', array('action' => 'add-tshirt-size')));
        $this->form->prepare();
        
        echo $this->form()->openTag($this->form);
    ?>  
    <div style="display: none;" class="mws-form-message error" id="mws-validate-error"></div>
    
    <div class="mws-form-inline">
         <div class="mws-form-row">
              <div class="mws-form-item large">
                  <label for="size">TShirt sizes must be in the following format: "S", "M", "L", "XL", "XXL", or "XXL" only.</label>
                  <input type="text" name="size" id="size" class="mws-textinput required" placeholder="T-Shirt Size">
             
             	  <script type="text/javascript">
             	      $('#size').blur(function() {
						   var items = new Array("S", "M", "L", "XL", "XXL", "XXXL");

						   
             	      });
             	  </script>
              </div>
         </div>
                                
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php
                       echo $this->formRow($this->form->get('size_inch'));
                   ?>
              </div>
         </div>
           
         <div class="mws-button-row">
             <?php 
                 echo $this->formSubmit($this->form->get('submit'));
                 
                 echo $this->form()->closeTag();
             ?>
         </div>
     </div>    	
  </div> 
</div>