<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Add User</span>
    </div>
    
    <div class="mws-panel-body">
    <?php 
        $this->form->setAttribute('action', $this->url('admin', array('action' => 'add-user')));
        $this->form->prepare();
        
        echo $this->form()->openTag($this->form);
    ?>  
    <div style="display: none;" class="mws-form-message error" id="mws-validate-error"></div>
    
    <div class="mws-form-inline">
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('username'));
                   ?>
              </div>
         </div>
                                
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php
                       echo $this->formRow($this->form->get('password'));
                   ?>
              </div>
         </div>
                                
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php
                       echo $this->formRow($this->form->get('first_name'));
                   ?>
              </div>
         </div>
                               
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('last_name'));
                   ?>                
              </div>
         </div>
         
         <div class="mws-form-row">
              <div class="mws-form-item large">
                  <label for="gender">Gender</label>
                  <?php 
                      echo $this->formSelect($this->form->get('gender'));
                  ?>            
              </div>
         </div>
         
          <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('address'));
                   ?>                
              </div>
         </div>
         
          <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('city'));
                   ?>                
              </div>
         </div>
         
         <div class="mws-form-row">
             <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('state'));
                   ?>                
             </div>
         </div>
         
         <div class="mws-form-row">
             <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('zipcode'));
                   ?>                
             </div>
         </div>
         
         <div class="mws-form-row">
             <div class="mws-form-item large">
                 <label for="country">Country:</label>
                 <?php 
                       echo $this->formSelect($this->form->get('country'));
                 ?>              
             </div>
         </div>
         
         <div class="mws-button-row">
             <?php 
                 echo $this->formSubmit($this->form->get('add_user_submit'));
                 
                 echo $this->form()->closeTag();
             ?>
         </div>
     </div>    	
  </div> 
</div>