<style>
.mws-panel {width:auto !important; }
</style>
<!--<div class="mws-panel grid_10">-->
<div class="mws-panel ">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1"><?=$this->pageHeading?></span>
    </div>
    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix ">
            <ul>
            	<li><a class="mws-ic-16 ic-accept" href="<?php echo $this->url(array('controller'=>'campaign', 'action'=>'add-instructions'), 'default', true)?>" title="Add">Add</a></li>
                <li><a class="mws-ic-16 ic-cross" href="javascript:void(0)" title="Delete" >Delete</a></li> <!-- onclick="deleteitem()" -->
            </ul>
        </div>
        <!--<table class="mws-table">-->
         <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th><input type="checkbox" name="deletebcchk" id="deletebcchk" onclick="return checkall(this)" /></th>
                    <th>Instruction Title</th>                    
                    <th>Instruction Description</th>
                    <th width="5%" class="">Edit</th>
                </tr>
            </thead>
            <tbody>
             <?php
             
			for($i=0;$i<count($this->sql);$i++) { ?>
                <tr class="gradeX">
                    <td><?=$i+1;?></td>
                    <td>
                        <input name='check<?=$i;?>' id='check<?=$i+1;?>' value='<?=$this->sql[$i]['instructuion_ID'];?>' 
                            onchange='return check_check("bcdel","deletebcchk")' type='checkbox'>
                        <script> 
                            $('#bcdel').html(''); document.getElementById('deletebcchk').checked = false;
                        </script>
                    </td>                  
  
                    <td> <?=$this->sql[$i]['instruction_title']?></td>  
                    <td> <?=$this->sql[$i]['instuction_description']?></td>                 
                   	<td class="center">
                        <a href="<?=APPLICATION_URL_ADMIN?>campaign/editinstruction/id/<?=$this->sql[$i]['instructuion_ID']?>">
			            	<img src="<?=APPLICATION_URL_ADMIN;?>css/icons/16/edit.png" border='0' />
			            </a>
			        </td> 
                    
            <?php }?> 
                       
                       
               
            </tbody>
        </table>
    </div>    	
</div>
<script>


function popitup(url) {
	newwindow=window.open(url,'name','height=700,width=900,scrollbars=1');
	if (window.focus) {newwindow.focus()}
	return false;
}
function deleteitem()
{
	var r= "";
	var s="";
	var selected=false;
	for(var i=1;document.getElementById('check'+i);i++){
		if(document.getElementById('check'+i).checked==true){	
			r += document.getElementById('check'+i).value+"|";
			selected = true;
		}
	}	
	
	r += '0';
	if(selected){
		var confirmation = confirm("Are you sure want to delete ?");
		if(confirmation!=true){
			return false;
		}	
	
		$.ajax({ url: "<?=APPLICATION_URL_ADMIN."campaign/deletecamp"?>",
		type: "POST",
		data: ({Id:r}),
		success: function(data){	
		//alert(data);		
			 window.location.href=window.location.href;
		}});
	} else {
		alert('Please choose a record to delete.');
	}
}
function changestatus(Id,Status)
{
    $.ajax({ 
				type: "POST", 
				url: "<?=APPLICATION_URL_ADMIN?>campaign/changestatus", 
				data: ({Id:Id,Status:Status}),
				cache: false, 
				success: function(data){				 
				  window.location.href=window.location.href;
			    }
		  });
}
 
function checkall(thisid)
{
  for(var i=1;document.getElementById('check'+i);i++)
  	{
  		if(document.getElementById(thisid.id).checked==true){document.getElementById('check'+i).checked = true;}
  		if(document.getElementById(thisid.id).checked==false){document.getElementById('check'+i).checked = false;}
	}	
}
</script>