<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Tee For All Configuration</span>
    </div>
    
    <div class="mws-panel-body">
    <?php 
        $this->form->setAttribute('action', $this->url('admin', array('action' => 'configuration')));
        $this->form->prepare();
        
        echo $this->form()->openTag($this->form);
    ?>
         
    <div class="mws-form-inline">
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('site_title'));
                   ?>
              </div>
         </div>
                                
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php
                       echo $this->formRow($this->form->get('site_description'));
                   ?>
              </div>
         </div>
                                
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php
                       echo $this->formRow($this->form->get('site_keywords'));
                   ?>
              </div>
         </div>
                               
         <div class="mws-form-row">
              <div class="mws-form-item large">
                   <?php 
                       echo $this->formRow($this->form->get('admin_email'));
                   ?>                
              </div>
         </div>
          
         <div class="mws-button-row">
             <?php 
                 echo $this->formSubmit($this->form->get('submit'));
             ?>
         </div>
     </div>    	
  </div> 
</div>