<div class="mws-panel grid_10">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1">Contact Sellers [Who launched the campaign]</span>
    </div>

<script type="text/javascript">
function validformdata() { 
	var x = document.getElementById("allusers").checked;
	
	if (!x) {
		if (document.getElementById('rightValues').value == '') {
			alert("Please select at least one user for sending mails");	
		} else {
			return true;
		}
    } else {
		return true;
	}

	return false;
}
</script>	
    <div class="mws-panel-body">
	 <form name="myform" id="myform" class="mws-form" 
	 action="<?php echo $this->url('admin', array('action'=> 'users-send-mail')); ?>" method="post" onsubmit="return validformdata();">

        <section >
    		<div>
       		<select id="leftValues" size="15" multiple>
				 <?php foreach ($this->contact_users as $cusers) {	?>
					<option value="<?php echo $cusers['username']; ?>
					::<?php echo $cusers['user_id']; ?>::
					<?php echo $cusers['public_name']?>" style="margin:2px 0px">
					<?php echo $cusers['username']; ?></option>
				<?php } ?>

			</select>
	    </div>
	    <div>
       	 <input type="button" id="btnLeft" value="&lt;&lt;" />
	        <input type="button" id="btnRight" value="&gt;&gt;" />
	    </div>
	    <div>
       	 <select id="rightValues" size="13" name="rightValues[]" multiple>
	           
       	 </select>
		 <div style="margin-top: 10px; width: 307px;">
		 	<input type="checkbox" value="1" id="allusers" name="allusers" >Send Mail To All Users 
		 	<input type="submit" id="sendmail" name="sendmail" value="Send Mail" style="float: right; margin-left: 81px;">
		 </div>
	    </div>
	</section>
	</form>
	</div>    	
</div>

<style type="text/css">
select {
    width: 200px;
    box-sizing: border-box;
}

section {
    padding: 8px;
    background-color: #f0f0f0;
    overflow: auto;
}

section > div {
    float: left;
    padding: 4px;
}

section > div + div {
    width: 40px;
    text-align: center;
}
</style>

<script type="text/javascript">
$("#btnLeft").click(function () {
    var selectedItem = $("#rightValues option:selected");
    $("#leftValues").append(selectedItem);
});

$("#btnRight").click(function () {
    var selectedItem = $("#leftValues option:selected");
    $("#rightValues").append(selectedItem);
});

$("#rightValues").change(function () {
    var selectedItem = $("#rightValues option:selected");
});
</script>