<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>

<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Edit T-Shirt Size</span>
    </div>
    
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" action="<?php echo $this->url('admin', 
            array('action' => 'update-size', 'id' => $this->id)); ?>" method="post" class="mws-form">
            
            <div style="display: none;" class="mws-form-message error" id="mws-validate-error"></div>
           
            <div class="mws-form-inline">
                <div class="mws-form-row">
                    <div class="mws-form-item large">
                         <?php echo $this->formRow($this->form->get('size')); ?>
                    </div>
                </div>
                
                <div class="mws-form-row">
                	<div class="mws-form-item">
                    	<?php echo $this->formRow($this->form->get('size_inch')); ?>
                	</div>
                
            </div>
            
            <div class="mws-button-row">
                <?php echo $this->formSubmit($this->form->get('submit')); ?>
            </div>
        </form>
    </div>    	
</div> 