<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>

<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Edit Email Templates</span>
    </div>
    
    <div class="mws-panel-body">
       <form name="myform" id="mws-validate" 
        action="<?php echo $this->url('admin', array('action' => 'updatetemplate', 'templateId' => $this->templateId),
            'default', true); ?>"  method="post" novalidate="novalidate" class="mws-form">
          <input type="hidden" name="save_or_send" id="save_or_send" value="1" />
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
            
            <div class="mws-form-inline">
                <div class="mws-form-row">
                    <label>Subject:</label>
                    <div class="mws-form-item large">
                        <input type="text" class="mws-textinput required" name="email_subject" value="">
                    </div>
                </div>
                
                <div class="mws-form-row">
                	<label>Message Body</label>
                	<div class="mws-form-item">
                        <!--<textarea id="elrte" cols="auto" rows="auto"></textarea>-->
                    	<?php echo $this->form->get('email_body'); ?>
                	</div>
            	</div>
            </div>
                            
            <div class="mws-button-row">
                 <input type="submit" value="Update Template" class="mws-button red">
            </div>
	</form>
</div>    	

<script type="text/javascript">
	function deleteRecord() { 
		var eIds = '';
		var userrows = new Array();
		var cboxes = document.getElementsByName("checkbox[]");

		for (i=0; i<cboxes.length; i++) { 
			if (cboxes[i].checked == true) {
				eIds += cboxes[i].value + ','; 
				userrows[i] = cboxes[i].value;
			}
		}
		
		if (eIds == "") {
			alert("Please select at least one record.");
			return;
		}


		if (confirm("Are you sure to delete these records?")) {
			$.ajax({ 
    			type: "POST", 
    			url: "/admin/delete-template/" + eIds,
    			data: { eID : eIds },
    			cache: false, 

    			success: function(data){
   					window.location = "/admin/email-template";		
	   			}
   			});
		}
	}
</script>
