<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>

<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check">Edit Email Templates</span>
    </div>
    
    <div class="mws-panel-body">
       <form name="myform" id="mws-validate" 
        action="<?php echo $this->url('admin', array('action' => 'update-templates', 'id' => $this->id)); ?>"  
        method="post" novalidate="novalidate" class="mws-form">
          <input type="hidden" name="save_or_send" id="save_or_send" value="1" />
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
            
            <div class="mws-form-inline">
                <div class="mws-form-row">
                    <label>Subject:</label>
                    <div class="mws-form-item large">
                        <input type="text" class="textInput" name="email_subject" 
                        value="<?php echo $this->subject; ?>" style="width: 400px; padding: 3px;">
                    </div>
                </div>
                
                <div class="mws-form-row">
                	<label>Message Body</label>
                	<div class="mws-form-item">
                        <textarea id="elrte" name="email_body" class="textInput" style="width: 90%; height: 400px;" cols="auto">
                        	<?php echo $this->body; ?>
                        </textarea>
                	</div>
            	</div>
            </div>
                            
            <div class="mws-button-row">
                 <?php echo $this->formSubmit($this->form->get('submit')); ?>
            </div>
	  </form>
   </div>  
</div>  	

