<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1">Manage Email Templates</span>
    </div>
                    
    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix">
            <ul>
                <li><a class="mws-ic-16 ic-accept" href="<?php echo $this->url('admin', array('action' => 'add-template')); ?>" 
                title="Add">Add</a></li>
                <li><a class="mws-ic-16 ic-cross" title="Delete" id="delete_records">Delete</a></li>
            </ul>
        </div>
           
                  
        <form method="post" name="myform" id="myform" action="">
             <table class="mws-datatable-fn mws-table">
                 <thead>
                     <tr>
                         <th width="45%">Template Name</th>
                         <th width="45%">Subject</th>
                         <th width="5%" class="">Edit</th>
                         <th width="5%" class=""></th>
                     </tr>
                 </thead>
                            
                 <tbody>
                     <?php
					       foreach ($this->email_tpls as $email_templates) {    
					 ?>
						<tr class="gradeX">
                            <td><?php echo $email_templates['template_title']; ?></td>
                            <td><?php echo $email_templates['email_subject']; ?></td>
                            <td class="center">
                               <a href="/admin/edit-template/<?php echo $email_templates['template_id']; ?>">
           							<img src="<?php echo $this->basePath(); ?>/admin/images/edit.png">
        					   </a>
                            </td>
            		
            		        <td>
            					<input type="checkbox" name="checkbox[]" id="checkbox[]" 
            					value="<?php echo $email_templates['template_id']; ?>">
            				</td>
						</tr>
					  <?php
							}
					  ?>
                   </tbody>
                </table> 
             </form> 
       </div>
</div>
            
            
<script type="text/javascript">
$('#delete_records').click(function() {
	if (confirm("Are you sure you want to delete these records?")) {
		var checked_items = $('input:checkbox[name="checkbox[]"]:checked')
		.map(function() { return $(this).val(); })
		.get()
		.join(",");

		$.ajax({
			type: "POST",
			url: "/admin/delete-templates",
			data: "id=" + checked_items,
			success: function() {
				window.location = "/admin/email-templates";
			}
		});

		return false;
	} 
});
</script>
