<!DOCTYPE html>
<html >
<head>
<meta charset="utf-8">

<!-- Apple iOS and Android stuff (do not remove) -->
<meta name="apple-mobile-web-app-capable" content="no">
<meta name="apple-mobile-web-app-status-bar-style" content="black">

<meta name="viewport" content="width=device-width,initial-scale=1">

<!-- Required Stylesheets -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/reset.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/text.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/fonts/ptsans/stylesheet.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/fluid.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/mws.style.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/icons/16x16.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/icons/24x24.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/icons/32x32.css" media="screen" />

<!-- Demo and Plugin Stylesheets -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/demo.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/colorpicker/colorpicker.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/imgareaselect/css/imgareaselect-default.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/fullcalendar/fullcalendar.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/fullcalendar/fullcalendar.print.css" media="print" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/chosen/chosen.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/prettyphoto/css/prettyPhoto.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/tipsy/tipsy.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/sourcerer/Sourcerer-1.2.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/jgrowl/jquery.jgrowl.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/fileinput/css/fileinput.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/spinner/ui.spinner.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/timepicker/timepicker.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/jui/jquery.ui.css" media="screen" />

<!-- Theme Stylesheet -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/css/mws.theme.css" media="screen" />

<!-- JavaScript Plugins -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/jquery.mousewheel-min.js"></script>

<!-- jQuery-UI Dependent Scripts -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/jquery-ui.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/spinner/ui.spinner.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/timepicker/timepicker-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/jquery.ui.touch-punch.min.js"></script>

<!-- Plugin Scripts -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/imgareaselect/jquery.imgareaselect.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/duallistbox/jquery.dualListBox-1.3.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/jgrowl/jquery.jgrowl-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/fileinput/js/jQuery.fileinput.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/fullcalendar/fullcalendar.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/datatables/jquery.dataTables-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/prettyphoto/js/jquery.prettyPhoto-min.js"></script>
<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/flot/excanvas.min.js"></script>
<![endif]-->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/flot/jquery.flot.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/flot/jquery.flot.pie.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/flot/jquery.flot.stack.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/flot/jquery.flot.resize.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/colorpicker/colorpicker-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/tipsy/jquery.tipsy-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/sourcerer/Sourcerer-1.2-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/placeholder/jquery.placeholder-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/validate/jquery.validate-min.js"></script>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/elrte/js/elrte.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/plugins/elfinder/js/elfinder.min.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/elrte/css/elrte.full.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/admin/plugins/elfinder/css/elfinder.css" media="screen" />

<!-- Core Script -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/mws.js"></script>

<!-- Themer Script (Remove if not needed) -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/themer.js"></script>



<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/demo.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin/js/demo.formelements.js"></script>



<script src="<?php echo $this->basePath() ?>/js/general.js" type="text/javascript"></script>
<title><?php echo $this->headTitle('Tee For All'); ?></title>
</head>
<body>

	<!-- Themer (Remove if not needed) -->  
	<div id="mws-themer" style="display:none;">
        <div id="mws-themer-content">
        	<div id="mws-themer-ribbon"></div>
            <div id="mws-themer-toggle"></div>
        	<div id="mws-theme-presets-container" class="mws-themer-section">
	        	<label for="mws-theme-presets">Color Presets</label>
            </div>
            <div class="mws-themer-separator"></div>
        	<div id="mws-theme-pattern-container" class="mws-themer-section">
	        	<label for="mws-theme-patterns">Background</label>
            </div>
            <div class="mws-themer-separator"></div>
            <div class="mws-themer-section">
                <ul>
                    <li class="clearfix"><span>Base Color</span> 
                    	<div id="mws-base-cp" class="mws-cp-trigger"></div>
                    </li>
                    
                    <li class="clearfix"><span>Highlight Color</span> 
                    	<div id="mws-highlight-cp" class="mws-cp-trigger"></div>
                    </li>
                    
                    <li class="clearfix"><span>Text Color</span>
                    	<div id="mws-text-cp" class="mws-cp-trigger"></div>
                    </li>
                    
                    <li class="clearfix"><span>Text Glow Color</span> 
                    	<div id="mws-textglow-cp" class="mws-cp-trigger"></div>
                    </li>
                    
                    <li class="clearfix"><span>Text Glow Opacity</span> 
                    	<div id="mws-textglow-op"></div>
                    </li>
                </ul>
            </div>
            <div class="mws-themer-separator"></div>
            <div class="mws-themer-section">
	            <button class="mws-button red small" id="mws-themer-getcss">Get CSS</button>
            </div>
        </div>
        
        <div id="mws-themer-css-dialog">
        	<form class="mws-form">
            	<div class="mws-form-row">
		        	<div class="mws-form-item">
                    	<textarea cols="auto" rows="auto" readonly="readonly"></textarea>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Themer End -->

	<!-- Header -->
	<div id="mws-header" class="clearfix" style="width: auto;">



    
    	<!-- Logo Container -->
    	<div id="mws-logo-container">
        
        	<!-- Logo Wrapper, images put within this wrapper will always be vertically centered -->
        	<div id="mws-logo-wrap">
            	<a href="/admin">
            	<span style="float:left; font-size:25px; color:#fff;" >Tee For All</span>
                </a>
			</div>
        </div>
        
        <!-- User Tools (notifications, logout, profile, change password) -->
        <div id="mws-user-tools" class="clearfix">
        
        	<!-- Notifications -->
        	<div id="mws-user-notif" class="mws-dropdown-menu">
            	 
                
            </div>
            
            
            
            <!-- User Information and functions section -->
            <div id="mws-user-info" class="mws-inset">
            
            	<!-- User Photo -->
            	<div id="mws-user-photo">
                	<img src="<?php echo $this->basePath(); ?>/admin/example/profile.jpg" alt="User Photo" />
                </div>
                
                <!-- Username and Functions -->
                <div id="mws-user-functions">
                    <div id="mws-username">
                        Admin
                    </div>
                    <ul>
                    	 
                        <li><a href="/admin/changepassword">Change Password</a></li>
                        <li><a href="/logout">Logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Start Main Wrapper -->
    <div id="mws-wrapper">
    
    	<!-- Necessary markup, do not remove -->
		<div id="mws-sidebar-stitch"></div>
		<div id="mws-sidebar-bg"></div>
        
        <!-- Sidebar Wrapper -->
        <div id="mws-sidebar">
            <!-- Main Navigation -->
            <?php include('templates/left.phtml'); ?>
            
        </div>
        
        <!-- Main Container Start -->
        <div id="mws-container" class="clearfix">
        
        	<!-- Inner Container Start -->
            <div class="container">
            
            	<!-- Statistics Button Container -->
            	 
                
                <!-- Panels Start -->
                
                
            	<div class="mws-panel grid_8">
                	<?php echo $this->content; ?>
                <!-- Panels End -->
            	</div>
            <!-- Inner Container End -->
                       
            <!-- Footer -->
            <div id="mws-footer">
            	Copyright &copy; TeeForAll. <?php echo date("Y");?>. All Rights Reserved.
            </div>
            
        </div>
        <!-- Main Container End -->
        
    </div>
 </div>
</body>
</html>
