<form method="post" name="myform" id="myform" action="">
	<div class="mws-panel grid_8">
        <div class="mws-panel-header">
             <span class="mws-i-24 i-table-1">Manage Pages</span>
        </div>
                    
        <div class="mws-panel-body">
            <div class="mws-panel-toolbar top clearfix">
                <ul>
                	<li><a class="mws-ic-16 ic-accept" href="<?php echo $this->url('admin', array('action' => 'add-page')); ?>" 
                		title="Add">Add</a></li>
                	<li><a class="mws-ic-16 ic-cross" title="Delete" id="delete_records">Delete</a></li>
            	</ul>           
            </div>
                        
            <table class="mws-datatable-fn mws-table">
                <thead>
                    <tr>
                       <th width="45%">Page Title</th>
                       <th width="5%" class="">Edit</th>
                       <th width="3%"></th>
                    </tr>
                </thead>
                            
                <tbody>
                    <?php
						foreach ($this->pages as $page) {
					?>
						<tr class="gradeX">
                           <td><?php echo $page['page_title']; ?></td>
                                       
                           <td class="center">
                               <a href="/admin/edit-page/<?php echo $page['page_id']; ?>">
            					   <img src="<?php echo $this->basePath() ;?>/admin/css/icons/16/edit.png" border='0' />
            				   </a>
           				   </td> 
                                        
                           <td>
                               <input type="checkbox" name="checkbox[]" id="checkbox[]" value="<?php echo $page['page_id']; ?>">
                           </td>
	                    </tr>
						<?php
							}
						?>
                    </tbody>
             </table>
          </div>
   </div>
</form>
            
<script type="text/javascript">
$('#delete_records').click(function() {
	if (confirm("Are you sure you want to delete these records?")) {
		var checked_items = $('input:checkbox[name="checkbox[]"]:checked')
		.map(function() { return $(this).val(); })
		.get()
		.join(",");

		$.ajax({
			type: "POST",
			url: "/admin/delete-page",
			data: "id=" + checked_items,
			success: function() {
				window.location = "/admin/pages";
			}
		});

		return false;
	} 
});
</script>

            