<form method="post" name="myform" id="myform" 
	action="<?php echo $this->url('admin', array('action' => 'tshirt-size')); ?>">
     <div class="mws-panel grid_8">
         <div class="mws-panel-header">
             <span class="mws-i-24 i-table-1">Manage TShirt Sizes</span>
         </div>
                    
         <div class="mws-panel-body">
             <div class="mws-panel-toolbar top clearfix">
                 <ul>
                    <li>
                    <li><a class="mws-ic-16 ic-accept" href="<?php echo $this->url('admin', array('action' => 'add-tshirt-size')); ?>" title="Add">Add</a></li>
                    <li><a class="mws-ic-16 ic-cross" title="Delete" id="delete_records">Delete</a></li>
                 </ul>
             </div>
                        
             <table class="mws-datatable-fn mws-table">
                 <thead>
                    <tr>
                       <th width="5%">No.</th>
                       <th><input type="checkbox" name="deletebcchk" id="deletebcchk"></th>
                       <th width="45%">Size</th>
                       <th width="45%">In Inches</th>
                       <th width="5%" class="">Edit</th>
                    </tr>
                 </thead>
                            
                 <tbody>
                    <?php
                    
                    $i = 0;
                    
						 foreach ($this->tshirt_sizes as $sizes) {
						     $i++;
					?>
						<tr class="gradeX">
                           <td><?php echo $i; ?></td>
                           
                           <td>
                               <input name="checkbox[]" id="check<?php echo $i; ?>"
                                value="<?php echo $sizes->size_id; ?>" type="checkbox">
                           </td>
                          
                           <td><?php echo $sizes->size; ?></td>
                                       
                           <td><?php echo $sizes->size_inch; ?></td>
                                         
                           <td class="center">
                               <a href="/admin/edit-tshirt-size/<?php echo $sizes->size_id; ?>">
            						<img src="<?php echo $this->basePath(); ?>/admin/css/icons/16/edit.png" border='0'>
                               </a>
           				   </td> 
                        </tr>
						<?php
								}
						?>
                   </tbody>
                </table>
           </div>
     </div>
</form>

<script type="text/javascript">
$('#delete_records').click(function() {
    if (confirm("Are you sure you wish to delete the selected rows?")) {
    	var checked_items = $('input:checkbox[name="checkbox[]"]:checked')
		.map(function() { return $(this).val(); })
		.get()
		.join(",");

		$.ajax({
			type: "POST",
			url: "/admin/delete-tshirt-size",
			data: "id=" + checked_items,
			success: function() {
				window.location.href = "/admin/tshirt-size";
			}
		});

		return false;
    }
});

$('#deletebcchk').click(function() {
	$('input:checkbox[name="checkbox[]"]').attr("checked", "checked");
});
</script>




            
            