<div class="mws-panel grid_10">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1">Manage Users</span>
    </div>
    
    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix">
            <ul>
                <li><a class="mws-ic-16 ic-cross" href="javascript:void(0)" title="Delete" onclick="deleteitem()">Delete</a></li>
            </ul>
        </div>
        
         <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th><input type="checkbox" name="deletebcchk" id="deletebcchk" onclick="return checkall(this)" /></th>
                  
                     
                    <th>Email Address</th>
                    <th>User Status</th>
                </tr>
            </thead>
            <tbody>
             <?php
                $cClass = "gradeX odd";
					
					foreach ($this->users as $user) {
					?>
                    
                <?php
                    if ($user->user_status == 1) { $image ='tick.png';   }
                    
                    if ($user->user_status == 0) { $image ='cross.png';  }
                    
                    if ($cClass == "gradeX odd") {
                        $cClass = "gradeX even";
                    } else {
                        $cClass = "gradeX odd";
                    }	
                    ?>
                        <tr class="<?php echo $cClass; ?>">
                            <?php for ($i=0; $i<count($this->users); $i++) { ?>
                            <td><?php echo $i + 1; ?></td>
                            <td>
                                <input name='check<?php echo $i;?>' id='check<?php echo $i + 1; ?>' 
                                value='<?php $user->user_id; ?>' 
                                    onchange='return check_check("bcdel","deletebcchk")' type='checkbox'>
                                 <?php } ?>
                                <script> 
                                    $('#bcdel').html(''); document.getElementById('deletebcchk').checked = false;
                                </script>
                            </td>
                            
          
                            <td><?php echo $user->username; ?></td>
                            
                            <td>
                       <a href="/admin/change-user-status/<?php echo $user->user_id; ?>"> 
                                   <?php 
		   				if ($this->users->user_status == 1) {
			   			   $status = $user->user_status;
						 ?>
              				<img src="<?php echo $this->basePath(); ?>/admin/images/tick.gif" onClick="f1('<?php echo $user->user_id; ?>', '<?php echo $status; ?>');">
			   			<?php
						}
							if ($user->user_status == 0) {
								$status = $user->user_status;
						 ?>
						 
                 		 	<img src="<?php echo $this->basePath(); ?>/admin/images/cross.png" onClick="f1('<?php echo $user->user_id; ?>', '<?php echo $status; ?>');">
                 		<?php  
		    			   } 
						?>
          				 </a>                 
                            </td>
                        </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>    	
</div>
<script type="text/javascript">

function deleteitem() {
	var r = "";
	var s = "";
	var selected = false;
	
	for (var i=1; document.getElementById('check' + i); i++) {
		if (document.getElementById('check' + i).checked == true) {	
			r += document.getElementById('check' + i).value + "|";
			selected = true;
		}
	}	
	
	r += '0';
	
	if (selected) {
		var confirmation = confirm("Are you sure want to delete?");
		
		if (confirmation != true) {
			return false;
		}	
	
		$.ajax({ 
			url: "/admin/delete-user",
			type: "POST",
			data: { id : r },
			success: function(data) {			
			 	window.location.href = window.location.href; // ?????
			}
		});
	} else {
		alert('Please choose a record to delete.');
	}
}


function changestatus(id, status) {
    $.ajax({ 
		type: "POST", 
		url: "/admin/change-user-status", 
		data: { id : id, status : status},
		cache: false, 
		success: function(data) {				 
			window.location.href = window.location.href; // ???
		}
	});
}
 
function checkall(thisid) {
	for (var i=1; document.getElementById('check' + i); i++) {
  		if (document.getElementById(thisid.id).checked == true) {
  	  		document.getElementById('check' + i).checked = true;
  	  	}
  	  	
  		if (document.getElementById(thisid.id).checked == false) {
  	  		document.getElementById('check' + i).checked = false;
  	  	}
	}	
}
</script>