<div class="mws-panel grid_10">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1">Manage Users</span>
    </div>
    
    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix">
            <ul>
                <li><a class="mws-ic-16 ic-accept" href="<?php echo $this->url('admin', array('action' => 'add-user')); ?>" 
                title="Add">Add User</a></li>
                
                <li><a class="mws-ic-16 ic-accept" id="edit-users" href="<?php echo $this->url('admin', array('action' => 'edit-user')); ?>" 
                title="Edit">Edit User</a></li>  
                
                <li><a class="mws-ic-16 ic-cross" id="delete_records" title="Delete">Delete User</a></li>      
            </ul>
        </div>
        
         <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>
                    <th>Check All Rows <input type="checkbox" name="deletebcchk" id="deletebcchk"></th>
                    <th>Email Address</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
             <?php
                $cClass = "gradeX odd";
					
                $i = 0;
                
					foreach ($this->users as $user) {
					    $i++;
					?>
                    
                <?php
                    //if ($user->user_status == 1) { $image = 'tick.png';   }
                    
                    //if ($user->user_status == 0) { $image = 'cross.png';  }
                    
                    if ($cClass == "gradeX odd") {
                        $cClass = "gradeX even";
                    } else {
                        $cClass = "gradeX odd";
                    }	
                    ?>
                        <tr class="<?php echo $cClass; ?>">
                            <td>
                                <input name="checkbox[]" id="<?php echo $i; ?>"
                                value="<?php echo $user->user_id; ?>" type="checkbox">
                            </td>
                            
          
                            <td><?php echo $user->username; ?></td>
                            
                            <td><?php echo $user->first_name . " " . $user->last_name; ?>
          			 	</tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>    	
</div>


<script type="text/javascript">
$('#delete_records').click(function() {
    if (confirm("Are you sure you wish to delete the selected rows?")) {
    	var checked_items = $('input:checkbox[name="checkbox[]"]:checked')
		.map(function() { return $(this).val(); })
		.get()
		.join(",");

		$.ajax({
			type: "POST",
			url: "/admin/delete-user",
			data: "id=" + checked_items,
			success: function() {
				window.location = "/admin/users";
			}
		});

		return false;
    }
});


$('#deletebcchk').click(function() {
	$('input:checkbox[name="checkbox[]"]').attr("checked", "checked");
});

// stupid thing
$('#change-user-status').click(function() {
	var id = $('input:checkbox[name="checkbox[]"]:checked');
	
	$.ajax({
		type: "POST",
		url: "/admin/change-user-status",
		data: { id : id, status : status },
		cache: false,
		success: function(data) {
			window.location.href = window.location.href;
		}
	});
});

$('#edit-users').click(function(e) {
	var id = $('input:checkbox[name="checkbox[]"]:checked')
	.map(function() { return $(this).val(); } )
	.get();

	$.ajax({
		type: "POST",
		url: "/admin/edit-user",
		data: "id=" + id,
		success: function(data) {
			window.location.href = "/admin/edit-user/" + id;
		}
	});

	return false;
});
</script>