<!--------------Footer--------------->
<footer>
    <div class="zerogrid">
        <div class="footer_left">
            <p>&nbsp; <!-- Tee For All allows you to crowdfund awesome custom apparel. --></p>
            <p>
                <a href="<?php echo $this->url('info', array('action' => 'termsofservice')); ?>">Terms</a>
                &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('info', array('action' => 'privacypolicy')); ?>">Privacy</a>
                &nbsp;&nbsp;&nbsp;<a href="#">Refund Policy</a>
                &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('info', array('action' => 'shippingrates')); ?>">Shipping Rates</a>
                &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('info', array('action' => 'contactus')); ?>">Contact Us</a>
            </p>
            <p>
                <a href="#">Features</a>
                &nbsp;&nbsp;&nbsp;<a href="#">FAQ</a>
                &nbsp;&nbsp;&nbsp;<a href="#">Jobs</a>
                &nbsp;&nbsp;&nbsp;<a href="#">Press Kit</a>
                &nbsp;&nbsp;&nbsp;<a href="#">DMCA Notice</a>
            </p>
        </div>
        <div class="footer_right">
            <div class="footer_logo"><a href="<?php echo $this->serverUrl(); ?>"><img src="<?php echo $this->basePath('/images/logo.png'); ?>" /></a></div>
            <div class="footer_social">
                <a href="http://www.google.com/+/learnmore/hangouts/?gpsrc=insebr&gclid=CLuK0dOF27UCFdFt6wodZXEAwQ"><img src="<?php echo $this->basePath('/images/gp_ic.png'); ?>"/></a>
                <a href="http://www.linkedin.com/"><img src="<?php echo $this->basePath('/images/in_ic.png'); ?>"/></a>
                <a href="http://www.youtube.com/"><img src="<?php echo $this->basePath('/images/tw_ic.png'); ?>"/></a>
                <a href="https://twitter.com/"><img src="<?php echo $this->basePath('/images/fb_ic.png'); ?>"/></a>
                <a href="https://www.facebook.com/"><img src="<?php echo $this->basePath('/images/u_ic.png'); ?>"/></a>
            </div>
        </div>
    </div>
    <div class="zerogrid">
        <div class="copyeright_content">
            TeeForAll &copy; 2015 All Rights Reserved
        </div>
    </div>
</footer>
<script>
function fbshare()
{
    window.open ("http://www.facebook.com", "Facebook_Share","menubar=1,resizable=1,width=900,height=500");
}

function tweetshare()
{
    window.open ("http://twitter.com", "Twitter_Share","menubar=1,resizable=1,width=900,height=500");
}

function youtubeshare()
{
    window.open ("http://www.youtube.com", "Youtube_Share","menubar=1,resizable=1,width=900,height=500");
}
</script>



