<?php
$userid = $this->loggedIn;
$myControllerName=$this->controller;
$myActionName=$this->action;

$draftct = $this->service('Campaign\Storage\Draft')->getCountForUser($userid);
$active = $this->service('Campaign\Storage\Campaign')->getCountForUser($userid, 1);
$end = $this->service('Campaign\Storage\Campaign')->getCountForUser($userid, 0);

if($myControllerName=="about" || $myControllerName=="myaccount" || $myControllerName=="shippingrates" || $myControllerName=="privacypolicy" || $myControllerName=="termsofservice" || $myControllerName=="contactus") {?>
    <!--------------start rsponsive left menu--------------->
    <div class="work_left_responsive">
        <?php if($myControllerName=="about" || $myControllerName=="shippingrates" || $myControllerName=="privacypolicy" || $myControllerName=="termsofservice" || $myControllerName=="contactus") { ?>
        <div class="mene_about_responsive">
            <div class="heading_menu_how_responsive">
              <h3>About</h3>
              <li><a href="<?php echo $this->url('campaign', array('action' => 'shippingrates')); ?>">Shipping rates</a></li>
            </div>
        </div>
        <div class="menu_policies_responsive">
            <div class="heading_menu_how_responsive">
              <h3>Policies</h3>
              <li><a href="<?php echo $this->url('info', array('action' => 'privacypolicy')); ?>">Privacy policy</a></li>
              <li><a href="<?php echo $this->url('info', array('action' => 'termsofservice')); ?>">Terms of service</a></li>
              <li><a href="<?php echo $this->url('info', array('action' => 'contactus')); ?>">Contact Us</a></li>
            </div>
        </div>
        <?php } ?>
        <?php if(($mySession->TeeLoggedID!="")) { ?>
        <div class="<?php if($myControllerName == "about") { ?>menu_policies_responsive<?php } else { ?>mene_about_responsive<?php } ?>">
            <?php if($myControllerName !== "about" && $myControllerName!=="shippingrates"  && $myControllerName!=="privacypolicy" && $myControllerName!=="termsofservice" && $myControllerName!=="contactus"): ?>
            <div class="heading_menu_how_responsive">
                <h3>My Account</h3>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'activecampaign')); ?>">Active
                            <?php if($active>0)    { ?>
                            <span class="badge badge-info badge-small"><?=$active?> </span>
                            <?php    }  ?>
                </a><li>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'endedcampaign')); ?>">Ended
                            <?php if($end>0){ ?>
                            <span class="badge badge-info badge-small"> <?=$end?> </span>
                            <?php }  ?>
                </a></li>

                <li><a href="<?php echo $this->url('myaccount', array('action' => 'drafts')); ?>">Drafts
                            <?php if($draftct>0) {     ?>
                            <span class="badge badge-info badge-small"><?=$draftct?></span>
                            <?php } ?>
                </a></li>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'profile')); ?>">Profile</a></li>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'changepassword')); ?>">Change Password</a></li>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'referfriends')); ?>">Refer a Friend</a></li>
            </div>
            <?php endif; ?>
        </div>
        <?php } ?>
    </div>
    <!--------------end rsponsive left menu--------------->
        <div class="work_left">
            <?php if($myControllerName=="about" || $myControllerName=="shippingrates"  || $myControllerName=="privacypolicy" || $myControllerName=="termsofservice" || $myControllerName=="contactus") { ?>
            <div class="mene_about">
                <div class="heading_menu_how">
                  <h3>About</h3>
                  <li><a href="<?php echo $this->url('info', array('action' => 'shippingrates')); ?>">Shipping rates</a></li>
                </div>
            </div>
            <div class="menu_policies">
                <div class="heading_menu_how">
                  <h3>Policies</h3>
                  <li><a href="<?php echo $this->url('info', array('action' => 'privacypolicy')); ?>">Privacy policy</a></li>
                  <li><a href="<?php echo $this->url('info', array('action' => 'termsofservice')); ?>">Terms of service</a></li>
                  <li><a href="<?php echo $this->url('info', array('action' => 'contactus')); ?>">Contact Us</a></li>
                </div>
            </div>
            <?php } ?>
            <?php if(($this->loggedId!="")) { ?>
            <div class="<?php if($myControllerName=="about") { ?>menu_policies<?php } else { ?>mene_about<?php } ?>">
                <?php if($myControllerName !== "about"): ?>
                <div class="heading_menu_how">
                    <h3>My Account</h3>
                    <li><a href="<?php echo $this->url('myaccount', array('action' => 'activecampaign')); ?>">Active
                            <?php if($active>0)    { ?>
                            <span class="badge badge-info badge-small"><?=$active?> </span>
                            <?php    }  ?>
                </a><li>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'endedcampaign')); ?>">Ended
                            <?php if($end>0){ ?>
                            <span class="badge badge-info badge-small"> <?=$end?> </span>
                            <?php }  ?>
                </a></li>

                <li><a href="<?php echo $this->url('myaccount', array('action' => 'drafts')); ?>">Drafts
                            <?php if($draftct>0) {     ?>
                            <span class="badge badge-info badge-small"><?=$draftct?></span>
                            <?php } ?>
                </a></li>
                    <li><a href="<?php echo $this->url('myaccount', array('action' => 'profile')); ?>">Profile</a></li>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'changepassword')); ?>">Change Password</a></li>
                <li><a href="<?php echo $this->url('myaccount', array('action' => 'referfriends')); ?>">Refer a Friend</a></li>
                </div>
                <?php endif; ?>
            </div>
            <?php } ?>
        </div>
<?php } ?>