<?php
$myControllerName=$this->controller;
$myActionName=$this->action;
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <!-- Basic Page Needs
  ================================================== -->
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
    <meta name="description" content="TeeForAll <?php if($this->pageTitle!="" ) { echo " - ".$this->pageTitle; } ?>">
    <meta name="author" content="TeeForAll">

    <!-- Mobile Specific Metas
  ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- CSS
  ================================================== -->
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/zerogrid.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/style.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/responsive.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/240.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/320.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/480.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/768.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('/css/bootstrap.min.css'); ?>">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl('/creator/css/jquery.fancyProductDesigner-fonts.css'); ?>" />

    <link rel="stylesheet" href="<?php echo $this->basePath('/css/jquery.countdown.css'); ?>" type="text/css">

    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="<?php echo $this->basePath('/js/html5.js'); ?>"></script>
        <script src="<?php echo $this->basePath('/js/css3-mediaqueries.js'); ?>"></script>
    <![endif]-->

    <script src="<?php echo $this->basePath('/js/jquery.min.js'); ?>" type="text/javascript"></script>
    <!--<script type="text/javascript" src="<?php echo $this->basePath('/admin/js/jquery-ui.js'); ?>"></script>-->
    <script src="<?php echo $this->basePath('/js/general.js'); ?>" type="text/javascript" ></script>

    <script src="<?php echo $this->basePath('/js/jquery.countdown.js'); ?>" type="text/javascript" ></script>
    <script src="<?php echo $this->basePath('/js/bootstrap.min.js'); ?>" type="text/javascript" ></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl('/creator/html2canvas.js'); ?>"></script>

    <script type="text/javascript" >
    $("#myInformationDiv").ready(function () { 
        $("#myInformationDiv2").show(1000);
    });
    setTimeout(
        function() {
            $("#myInformationDiv2").hide(
                "fast", function () {
                    // use callee so don't have to name the function
                    $(this).prev().hide("fast", arguments.callee);
                }
            );
        },
        7000
    );
    function showhide_commentbox(Stat,Id,Id1)
    {
        if (Stat!="") {
            $('#answer'+Id+Id1).slideToggle("slow");
        }
    }

    $(document).ready(function() {
        if(document.getElementById('frontDataValK').value=='front') {
            $('#onlyFrontDataK').css("display","block");
        } else {
            $('#bothdatakmanika').css("display","block");
        }
    });

    function showtee()
    {
        $('#Tees1').css("display","none");
        $('#Tees0').css("display","block");
    }

    function showtee1()
    {
        $('#Tees0').css("display","none");
        $('#Tees1').css("display","block");
    }
    </script>

    <link href='<?php echo $this->basePath('favicon.ico'); ?>' rel='icon' type='image/x-icon'/>
    <style>


    #Tees0
    {
        display:block;
    }

    #Tees1
    {
        display:none;
    }

    #onlyFrontDataK ,#bothdatakmanika
    {
        display:none;
    }

    .fpd-recreation div {
        position: relative;
        height: 570px;
        /*margin-left: -42px;*/
    }

    .fpd-recreation img,
    .fpd-recreation canvas,
    .fpd-recreation span {
        position: absolute;
    }
    </style>

</head>
<body id="page1">
    <input type="hidden" id="frontDataValK" value="" />
    <?php echo $this->flashMessenger()->render(); ?>
    <?php echo $this->render('campaign/layout/header_1'); ?>

    <?php if($myControllerName!="launchcampaign" && $myControllerName!="trackorder" && $myControllerName!="shippingrates") { ?>
    <!--------------header end--------------->
    <div class="banner">
      <div class="zerogrid">
        <div class="row block" style="margin-bottom:0px;">
          <div id="align_both">
            <div class="top_info">
              <div class="info_left" id="how_in_right">
                <?php echo $this->pageTitle; ?>
              </div>
              <div class="info_right" id="how_in_right_2">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!--------------top info end--------------->
    <section id="content">
        <div class="zerogrid">
            <div class="row block">
                <div class="work_both">
                    <?php if($this->action == "payment") {
                        echo $this->render('campaign/layout/csummary');
                    } else {
                        echo $this->render('campaign/layout/left');
                    } ?>
                    <div class="work_right">
                     <?php echo $this->layout()->content;?>
                    </div>
                </div>
            </div>

      </div>
    </section>
    <?php } elseif($this->controller == "campaign") { ?>
        <!--------------header end--------------->
        <div class="banner">
          <div class="zerogrid">
            <div class="row block" style="margin-bottom:0px;">
              <div id="align_both">
                <div class="top_info">
                  <div class="info_left" id="launch_campaign">
                    <?php echo $this->pageTitle; ?>
                </div>
                  <div class="info_right" id="launch_campaign_rgt">
                    <?php if($this->action == 'index' ) { ?>
                    <div id="KM-Price-Ctr" class="base_price_info" style="display:none;">Base Price:<span id="KM-Price">$ </span></div>
                    <?php } ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <?php echo $this->layout()->content; ?>


    <?php } elseif($myControllerName=="trackorder" || $myControllerName=="shippingrates") { ?>
        <!--------------header end--------------->
        <div class="banner">
          <div class="zerogrid">
            <div class="row block" style="margin-bottom:0px;">
              <div id="align_both">
                <div class="top_info">
                  <div class="info_left" id="launch_campaign">
                    <?php echo $this->pageTitle; ?>
                </div>
                  <div class="info_right" id="launch_campaign_rgt">
                    <?php if($myActionName=='index' ) { ?>
                    <div id="KM-Price-Ctr" class="base_price_info" style="display:none;">Base Price:<span id="KM-Price">$ </span></div>
                    <?php } ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--------------top info end--------------->
        <section id="content">
            <div class="zerogrid">
                <div class="row block">
                    <div class="work_both">
                        <?php if($myControllerName=="payment" && $myActionName=='index') {
                            echo $this->render('campaign/layout/csummary');
                        } else {
                            echo $this->render('campaign/layout/left');
                        } ?>
                        <div class="work_right">
                         <?php echo $this->layout()->content;?>
                        </div>
                    </div>
                </div>

          </div>
        </section>
    <?php } else {
        echo $this->layout()->content;
    }
    ?>

    <?php echo $this->render('campaign/layout/footer_1'); ?>
    <?php echo $this->inlineScript() ?>
</body>
</html> 